export const seedCategories = [
  {
    name: "Thokku Varieties",
    slug: "thokku",
    subtitle: "Slow-Cooked Relishes",
    tagline: "Hand-pounded spices, sun-cured aromatics, and cold-pressed gingelly oil.",
    description: "Every batch of our thokku is slow-simmered in small brass and stone pots using heirloom recipes handed down across generations.",
    image: "/assets/Thokku's/tomato_mix_.jpg",
    displayOrder: 1,
    isActive: true
  },
  {
    name: "Health Mix & Grains",
    slug: "health-mix",
    subtitle: "Pure Nourishment",
    tagline: "Sprouted whole grain nutrition for every age.",
    description: "Nourish your family with multi-grain sprouted mixes and traditional porridge powders prepared without artificial additives.",
    image: "/assets/Thokku's/karuppukavuni_pedestal_.jpg",
    displayOrder: 2,
    isActive: true
  },
  {
    name: "Ghee",
    slug: "ghee",
    subtitle: "Liquid Gold",
    tagline: "Cultured A2 bilona ghee — slow-churned the Vedic way.",
    description: "Prepared from grass-fed indigenous desi cow milk using the Vedic 5-step Bilona method. Naturally granular texture with an enchanting nutty aroma.",
    image: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?q=80&w=800&auto=format&fit=crop",
    displayOrder: 3,
    isActive: true
  },
  {
    name: "Masalas",
    slug: "masalas",
    subtitle: "Authentic Spice Blends",
    tagline: "Stone-ground whole spice blends roasted on iron tawa.",
    description: "Handcrafted masala blends using whole spices stone-ground fresh to preserve volatile oils, aroma, and authentic flavor depth.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop",
    displayOrder: 4,
    isActive: true
  },
  {
    name: "Skin & Hair Care",
    slug: "skin-hair",
    subtitle: "Nature's Apothecary",
    tagline: "Botanical formulations from native medicinal plants.",
    description: "Traditional botanical skincare and haircare crafted from native medicinal plants, handpicked and stone-ground to preserve active bio-nutrients.",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop",
    displayOrder: 5,
    isActive: true
  }
];

export const seedProducts = [
  // 1. Thokku
  {
    name: "Country Tomato (Nattu Thakkali) Mix",
    slug: "tomato-thokku",
    sku: "THK-TOM-250",
    category: "thokku",
    price: 240,
    compareAtPrice: 275,
    discount: 13,
    weight: "250g",
    image: "/assets/Thokku's/tomato_mix_.jpg",
    images: ["/assets/Thokku's/tomato_mix_.jpg"],
    shortDescription: "Ripe farm-fresh country tomatoes slow-reduced until thick and fragrant with aromatic curry leaves.",
    description: "Sun-ripened indigenous country tomatoes reduced to a velvety, rich consistency over a slow flame. Infused with freshly roasted aromatic spices, curry leaves, and unrefined wood-pressed oil.",
    ingredients: ["Farm Country Tomatoes", "Cold-Pressed Gingelly Oil", "Guntur Red Chilli", "Mustard Seeds", "Curry Leaves", "Tamarind Pulp", "Rock Salt", "Fenugreek", "Asafoetida"],
    howToUse: "An instant companion for idlis, rotis, poori, or mixed directly with steaming rice. Excellent spread for sourdough toast or wraps.",
    storage: "Keep in a cool, dry cupboard. Keep the rim clean and use a dry wooden or steel spoon. Keep refrigerated once opened.",
    shelfLife: "6 Months from date of packing",
    isVeg: true,
    badge: "Bestseller",
    available: true,
    stock: 85,
    rating: 4.9,
    reviewCount: 128,
    isFeatured: true
  },
  {
    name: "Karuveppilai (Curry Leaf) Mix",
    slug: "curry-leaf-thokku",
    sku: "THK-CRL-250",
    category: "thokku",
    price: 260,
    compareAtPrice: 295,
    discount: 12,
    weight: "250g",
    image: "/assets/Thokku's/curry_leaf_mix_.jpg",
    images: ["/assets/Thokku's/curry_leaf_mix_.jpg"],
    shortDescription: "Hand-harvested fresh curry leaves slow-roasted with black pepper, cumin, and cold-pressed gingelly oil.",
    description: "Rich in natural iron and antioxidants, our Karuveppilai thokku is prepared using fresh village curry leaves roasted slowly with stone-ground whole spices, tamarind, and unrefined wood-pressed oil.",
    ingredients: ["Fresh Village Curry Leaves", "Cold-Pressed Gingelly Oil", "Black Pepper", "Cumin Seeds", "Tamarind Pulp", "Guntur Red Chilli", "Himalayan Rock Salt", "Asafoetida"],
    howToUse: "Mix with hot steamed rice and melted A2 ghee for an iron-rich nourishing lunch. Pairs wonderfully with curd rice and idlis.",
    storage: "Store in a cool, dry place. Keep the jar tightly sealed. Refrigerate after opening.",
    shelfLife: "8 Months from date of packing",
    isVeg: true,
    badge: "Iron Rich",
    available: true,
    stock: 90,
    rating: 4.9,
    reviewCount: 94,
    isFeatured: true
  },
  {
    name: "Mudakathan Keerai (Balloon Vine) Mix",
    slug: "mudakathan-thokku",
    sku: "THK-MUD-250",
    category: "thokku",
    price: 270,
    compareAtPrice: 310,
    discount: 13,
    weight: "250g",
    image: "/assets/Thokku's/mudakathan_mix_.jpg",
    images: ["/assets/Thokku's/mudakathan_mix_.jpg"],
    shortDescription: "Traditional joint-care medicinal greens sautéed with shallots, tamarind, and cold-pressed gingelly oil.",
    description: "Mudakathan (Balloon Vine) is revered in Siddha and Ayurveda for joint comfort and mobility. Handpicked wild greens are slow-simmered with country tamarind, shallots, and fragrant roasted spices to eliminate bitterness while preserving potency.",
    ingredients: ["Fresh Mudakathan Leaves", "Cold-Pressed Gingelly Oil", "Small Onions (Shallots)", "Tamarind Extract", "Red Chilli", "Roasted Fenugreek", "Mustard", "Rock Salt"],
    howToUse: "Toss with hot rice, spread over warm dosas, or enjoy with idlis and porridge.",
    storage: "Store in a cool dry area. Always use a dry spoon. Refrigerate after opening.",
    shelfLife: "8 Months from date of packing",
    isVeg: true,
    badge: "Joint Care",
    available: true,
    stock: 60,
    rating: 5.0,
    reviewCount: 112,
    isFeatured: true
  },
  {
    name: "Pirandai (Adamant Creeper) Mix",
    slug: "pirandai-thokku",
    sku: "THK-PIR-250",
    category: "thokku",
    price: 280,
    compareAtPrice: 320,
    discount: 12,
    weight: "250g",
    image: "/assets/Thokku's/pirandai_mix_.jpg",
    images: ["/assets/Thokku's/pirandai_mix_.jpg"],
    shortDescription: "Tender adamant creeper stems roasted with whole spices to enhance gut health and bone strength.",
    description: "Known as 'Veldt Grape', Pirandai is celebrated in Tamil households for digestion and bone wellness. Tender stems are carefully cleaned, roasted with tamarind and stone-ground spices in cold-pressed sesame oil to deliver a delicious tangy relish.",
    ingredients: ["Tender Pirandai Stems", "Cold-Pressed Sesame Oil", "Tamarind Pulp", "Red Chillies", "Urad Dal", "Mustard Seeds", "Fenugreek", "Rock Salt", "Asafoetida"],
    howToUse: "Consume 1 spoonful with hot rice and ghee as the first course of your meal for digestive activation.",
    storage: "Keep in a cool dry place away from moisture. Refrigerate once opened.",
    shelfLife: "9 Months from date of packing",
    isVeg: true,
    badge: "Gut Health",
    available: true,
    stock: 75,
    rating: 4.9,
    reviewCount: 146,
    isFeatured: true
  },
  {
    name: "Poondu Milagu (Garlic & Pepper) Mix",
    slug: "poondu-milagu-thokku",
    sku: "THK-GAR-250",
    category: "thokku",
    price: 290,
    compareAtPrice: 330,
    discount: 12,
    weight: "250g",
    image: "/assets/Thokku's/poondu_milagu_mix_.jpg",
    images: ["/assets/Thokku's/poondu_milagu_mix_.jpg"],
    shortDescription: "Potent country garlic cloves slow-simmered with black pepper, tamarind, and cold-pressed gingelly oil.",
    description: "A time-tested immunity and digestion recipe featuring plump native garlic simmered with crushed Tellicherry black pepper, country tamarind, and unrefined wood-pressed gingelly oil. Warming, comforting, and packed with therapeutic goodness.",
    ingredients: ["Country Garlic", "Tellicherry Black Pepper", "Cold-Pressed Gingelly Oil", "Tamarind Pulp", "Guntur Red Chilli", "Roasted Fenugreek", "Mustard Seeds", "Rock Salt", "Asafoetida"],
    howToUse: "Stir 1-2 spoons with hot steamed rice and melted ghee, or pair with ragi mudde, idli, and plain rotis for comforting warmth.",
    storage: "Store in a cool, dry cupboard. Keep the jar tightly closed. Refrigerate after opening.",
    shelfLife: "9 Months from date of packing",
    isVeg: true,
    badge: "Immunity",
    available: true,
    stock: 95,
    rating: 5.0,
    reviewCount: 168,
    isFeatured: true
  },
  {
    name: "Mulaikattiya Payaru (Sprouted Moong) Mix",
    slug: "mulaikattiya-payaru-thokku",
    sku: "THK-MNG-250",
    category: "thokku",
    price: 250,
    compareAtPrice: 285,
    discount: 12,
    weight: "250g",
    image: "/assets/Thokku's/mulaikattiya_payaru_mix_.jpg",
    images: ["/assets/Thokku's/mulaikattiya_payaru_mix_.jpg"],
    shortDescription: "Sprouted green gram cooked with native spices, shallots, and ginger-garlic for wholesome protein.",
    description: "Nutrient-dense sprouted whole moong beans gently cooked with country spices, curry leaves, and unrefined oil. A hearty, protein-packed relish that elevates everyday meals.",
    ingredients: ["Sprouted Green Gram (Moong)", "Cold-Pressed Oil", "Country Shallots", "Curry Leaves", "Ginger", "Garlic", "Whole Spices", "Rock Salt"],
    howToUse: "Enjoy with roti, curd rice, dosas, or as a protein-rich savory mix with warm millets.",
    storage: "Store in cool dry cupboard. Refrigerate after opening.",
    shelfLife: "6 Months from date of packing",
    isVeg: true,
    badge: "Protein Rich",
    available: true,
    stock: 50,
    rating: 4.8,
    reviewCount: 88,
    isFeatured: false
  },
  {
    name: "Kili Mooku Mango Thokku",
    slug: "mango-thokku",
    sku: "THK-MNG-TOT",
    category: "thokku",
    price: 260,
    compareAtPrice: 295,
    discount: 12,
    weight: "250g",
    image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Grated raw totapuri mangoes simmered with roasted mustard, fenugreek, and cold-pressed sesame oil.",
    description: "Our signature raw mango thokku is crafted from fresh raw mangoes, finely grated and slow-cooked in cold-pressed sesame (gingelly) oil with a fragrant blend of freshly roasted mustard and fenugreek seeds. Perfect balance of tang, spice, and warmth.",
    ingredients: ["Raw Totapuri Mango", "Cold-Pressed Sesame Oil", "Red Chilli Powder", "Roasted Mustard Seeds", "Fenugreek Powder", "Himalayan Rock Salt", "Asafoetida (Hing)", "Turmeric"],
    howToUse: "Stir a generous spoonful into warm steamed rice with a dollop of ghee. Pairs exceptionally with curd rice, crispy dosas, and parathas.",
    storage: "Store in a cool, dry place away from direct sunlight. Always use a clean, dry spoon. Refrigerate after opening to preserve peak freshness.",
    shelfLife: "9 Months from date of packing",
    isVeg: true,
    badge: "Signature",
    available: true,
    stock: 120,
    rating: 4.9,
    reviewCount: 142,
    isFeatured: true
  },
  {
    name: "Tangy Gongura (Sorrel Leaf) Thokku",
    slug: "gongura-thokku",
    sku: "THK-GON-250",
    category: "thokku",
    price: 260,
    compareAtPrice: 290,
    discount: 10,
    weight: "250g",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Freshly harvested red-stem sorrel leaves tempered with whole garlic and crushed red chilies.",
    description: "Authentic red-stem gongura leaves handpicked and slowly sautéed in cold-pressed oil with whole crushed garlic and spicy dry red chilies. An irresistible earthy sour relish.",
    ingredients: ["Red-Stem Gongura Leaves", "Wood-Pressed Gingelly Oil", "Crushed Garlic", "Guntur Red Chillies", "Mustard Seeds", "Fenugreek", "Sea Salt"],
    howToUse: "Toss with piping hot rice, sliced raw onions, and pure desi cow ghee for the timeless royal experience.",
    storage: "Store in airtight jar in cool dark place. Refrigerate once opened.",
    shelfLife: "6 Months from date of packing",
    isVeg: true,
    badge: "Heirloom",
    available: true,
    stock: 65,
    rating: 4.7,
    reviewCount: 65,
    isFeatured: false
  },

  // 2. Health Mix & Grains
  {
    name: "Heritage Karuppu Kavuni (Black Rice) Mix",
    slug: "karuppu-kavuni-mix",
    sku: "HLT-KKV-500",
    category: "health-mix",
    price: 360,
    compareAtPrice: 410,
    discount: 12,
    weight: "500g",
    image: "/assets/Thokku's/karuppukavuni_pedestal_.jpg",
    images: ["/assets/Thokku's/karuppukavuni_pedestal_.jpg"],
    shortDescription: "Ancient royal black rice roasted and blended with sprouted millets, nuts, and dry ginger.",
    description: "Karuppu Kavuni (Forbidden Black Rice) was historically reserved for royalty due to its extraordinarily high anthocyanin antioxidant content. Stone-ground with sprouted grains and aromatic spices for royal health.",
    ingredients: ["Indigenous Karuppu Kavuni Rice", "Sprouted Ragi", "Sprouted Moong", "Almonds", "Cardamom", "Dry Ginger"],
    howToUse: "Boil 2 tablespoons in water or milk for 5 minutes to prepare a rich purple nutritious porridge.",
    storage: "Store in an airtight container away from moisture.",
    shelfLife: "9 Months from date of packing",
    isVeg: true,
    badge: "Antioxidant Rich",
    available: true,
    stock: 70,
    rating: 5.0,
    reviewCount: 118,
    isFeatured: true
  },
  {
    name: "Sprouted 14-Grain Multi-Millet Sathu Maavu",
    slug: "sprouted-health-mix",
    sku: "HLT-STM-500",
    category: "health-mix",
    price: 340,
    compareAtPrice: 390,
    discount: 13,
    weight: "500g",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Sprouted finger millet, pearl millet, foxtail, roasted grams, almonds, and dry ginger.",
    description: "A nutrient-dense traditional multigrain porridge powder. Whole grains and millets are carefully soaked, sprouted to unlock bio-availability, solar-dried, gently roasted on iron tawa, and finely ground with cardamoms and dry ginger.",
    ingredients: ["Sprouted Ragi (Finger Millet)", "Sprouted Kambu (Pearl Millet)", "Thinai (Foxtail Millet)", "Sprouted Green Gram", "Roasted Bengal Gram", "Almonds", "Cashews", "Dry Ginger (Sukku)", "Green Cardamom"],
    howToUse: "Mix 2 tbsp with 200ml water or milk without lumps. Cook on medium heat for 3-5 mins until smooth porridge forms. Sweeten with jaggery or enjoy salted with buttermilk.",
    storage: "Store in an airtight stainless steel or glass container after opening. Protect from dampness.",
    shelfLife: "9 Months from date of packing",
    isVeg: true,
    badge: "Bestseller",
    available: true,
    stock: 110,
    rating: 4.9,
    reviewCount: 189,
    isFeatured: true
  },
  {
    name: "Karupatti (Palm Jaggery) Millet Malt",
    slug: "palm-jaggery-millet-malt",
    sku: "HLT-MLT-400",
    category: "health-mix",
    price: 310,
    compareAtPrice: 350,
    discount: 11,
    weight: "400g",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Sprouted ragi malt sweetened with mineral-rich pure palm jaggery and roasted nuts.",
    description: "A ready-to-stir nutritious breakfast drink mix naturally sweetened with unbleached Udangudi palm jaggery. Rich in iron, calcium, and sustained energy without refined sugars.",
    ingredients: ["Sprouted Ragi Flour", "Pure Palm Jaggery (Karupatti)", "Roasted Almond Powder", "Cocoa Bean Powder (Hint)", "Cardamom"],
    howToUse: "Stir 2 tablespoons in a glass of hot milk or warm water. Instant, wholesome energy for children and adults.",
    storage: "Keep airtight in a cool dry space.",
    shelfLife: "6 Months from date of packing",
    isVeg: true,
    badge: "Natural Sweetener",
    available: true,
    stock: 60,
    rating: 4.7,
    reviewCount: 52,
    isFeatured: false
  },
  {
    name: "Herbal Golden Milk Immunity Mix",
    slug: "immunity-golden-mix",
    sku: "HLT-GLD-200",
    category: "health-mix",
    price: 320,
    compareAtPrice: 360,
    discount: 11,
    weight: "200g",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "High-curcumin Salem turmeric, wild ashwagandha, black pepper, Ceylon cinnamon, and nutmeg.",
    description: "An Ayurvedic nighttime elixir mix crafted with 5.5%+ curcumin organic Salem turmeric and potent adaptogenic herbs. Black pepper ensures maximum curcumin absorption for robust immune defense.",
    ingredients: ["Organic Salem Turmeric", "Wild Ashwagandha Root", "Ceylon Cinnamon", "Malabar Black Pepper", "Jaiphal (Nutmeg)", "Licorice (Mulethi)", "Green Cardamom"],
    howToUse: "Whisk 1/2 teaspoon into a cup of warm milk (dairy or almond/oat). Add raw honey or palm candy to taste.",
    storage: "Keep in a cool, dark cabinet. Avoid humid spots.",
    shelfLife: "12 Months from date of packing",
    isVeg: true,
    badge: "Go-To Pick",
    available: true,
    stock: 80,
    rating: 4.8,
    reviewCount: 76,
    isFeatured: false
  },

  // 3. Ghee
  {
    name: "Traditional A2 Desi Cow Bilona Ghee",
    slug: "a2-bilona-ghee",
    sku: "GHE-A2B-350",
    category: "ghee",
    price: 680,
    compareAtPrice: 750,
    discount: 9,
    weight: "350ml",
    image: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1628088062854-d1870b4553da?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Cultured curd churned using wooden bilona, slow-clarified over low wood-fire with betel & curry leaves.",
    description: "Prepared from grass-fed indigenous desi cow milk using the Vedic 5-step Bilona method. Curd is hand-churned in bi-directional wooden churners to extract makkhan, which is gently clarified over slow firewood. Naturally granular (danedaar) texture with an enchanting nutty aroma.",
    ingredients: ["Pure Cultured A2 Desi Cow Milk Fat", "Organic Curry Leaf Infusion", "Betel Leaf Extract"],
    howToUse: "Drizzle 1-2 teaspoons over steaming rice, dosas, dal, or warm milk before bedtime for nourishing vitality.",
    storage: "Store at ambient room temperature in a dry place. Do not refrigerate. Solidifies naturally in cooler weather.",
    shelfLife: "12 Months from date of packing",
    isVeg: true,
    badge: "Go-To Pick",
    available: true,
    stock: 140,
    rating: 5.0,
    reviewCount: 230,
    isFeatured: true
  },
  {
    name: "Heritage Turmeric & Pepper Infused Ghee",
    slug: "infused-turmeric-ghee",
    sku: "GHE-TRM-250",
    category: "ghee",
    price: 720,
    compareAtPrice: 800,
    discount: 10,
    weight: "250ml",
    image: "https://images.unsplash.com/photo-1631209121750-a9f656d28f17?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1631209121750-a9f656d28f17?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "A2 bilona ghee slow-infused with high-curcumin turmeric and Tellicherry black pepper for immunity.",
    description: "Our signature A2 bilona ghee gently infused over slow woodfire with organic Salem turmeric and whole Tellicherry black pepper. The piperine in pepper enhances curcumin absorption by up to 2000%. A deeply medicinal everyday cooking fat.",
    ingredients: ["A2 Bilona Ghee", "Organic Salem Turmeric (5.5% Curcumin)", "Tellicherry Black Pepper", "Curry Leaves"],
    howToUse: "Use as your daily cooking fat or drizzle over hot dal, rice, and soups. Excellent in warm turmeric milk.",
    storage: "Store at room temperature. Do not refrigerate.",
    shelfLife: "12 Months from date of packing",
    isVeg: true,
    badge: "Bestseller",
    available: true,
    stock: 55,
    rating: 4.9,
    reviewCount: 104,
    isFeatured: true
  },

  // 4. Masalas
  {
    name: "Authentic Chettinad Masala Powder",
    slug: "chettinad-masala",
    sku: "MSL-CHT-200",
    category: "masalas",
    price: 220,
    compareAtPrice: 260,
    discount: 15,
    weight: "200g",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Stone-ground kalpasi, marathi mokku, star anise and 18 whole spices for the legendary Chettinad flavor.",
    description: "The hallmark of authentic Chettinad cooking lies in its unique whole spices — kalpasi (stone flower), marathi mokku (dried flower pods), and star anise. Our blend uses these 18 rare spices, lightly roasted on iron tawa and stone-ground to a fine powder.",
    ingredients: ["Kalpasi (Stone Flower)", "Marathi Mokku", "Star Anise", "Black Stone Flower", "Bay Leaves", "Cinnamon", "Cloves", "Cardamom", "Pepper", "Cumin", "Fennel", "Mace", "Nutmeg", "Dried Red Chilli", "Coriander Seeds", "Turmeric"],
    howToUse: "Use 1-2 tsp per serving in gravies, biryanis, and curries. Blooms beautifully in hot oil or ghee.",
    storage: "Store in airtight glass jar away from direct sunlight.",
    shelfLife: "12 Months from date of packing",
    isVeg: true,
    badge: "Bestseller",
    available: true,
    stock: 90,
    rating: 4.9,
    reviewCount: 134,
    isFeatured: true
  },
  {
    name: "Heritage Sambar Powder (Kuzhambu Milagai Thool)",
    slug: "sambar-powder",
    sku: "MSL-SMB-250",
    category: "masalas",
    price: 180,
    compareAtPrice: 210,
    discount: 14,
    weight: "250g",
    image: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1505253758473-96b7015fcd40?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Toor dal-roasted blend of Byadgi chilli, coriander, cumin and curry leaves for the richest sambar.",
    description: "Our grandmother's sambar powder recipe using Byadgi red chillies for rich deep color, whole coriander and cumin lightly roasted with urad and chana dal, then stone-ground to an aromatic, coarse-ground powder that gives sambar its soul.",
    ingredients: ["Byadgi Red Chilli", "Coriander Seeds", "Cumin", "Urad Dal", "Chana Dal", "Black Pepper", "Curry Leaves (Dried)", "Turmeric", "Asafoetida"],
    howToUse: "Add 1-1.5 tsp per serving during sambar cooking. Also excellent in rasam and lentil gravies.",
    storage: "Keep in a dry airtight container.",
    shelfLife: "12 Months from date of packing",
    isVeg: true,
    badge: "Go-To Pick",
    available: true,
    stock: 85,
    rating: 4.8,
    reviewCount: 87,
    isFeatured: false
  },

  // 5. Skin & Hair Care
  {
    name: "Wild Brahmi (Vallarai) Leaf Powder",
    slug: "brahmi-vallarai-powder",
    sku: "SKN-BRH-150",
    category: "skin-hair",
    price: 220,
    compareAtPrice: 250,
    discount: 12,
    weight: "150g",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Shade-dried Asiatic Pennywort leaves — the Siddha herb for memory, hair growth, and skin glow.",
    description: "Centella Asiatica (Vallarai), revered in Siddha and Ayurvedic medicine for supporting brain function, hair growth, and collagen synthesis. Hand-harvested from clean forest beds and shade-dried to preserve active triterpenoids.",
    ingredients: ["100% Pure Shade-Dried Vallarai (Centella Asiatica) Leaves"],
    howToUse: "For hair: Mix with coconut oil, apply to scalp, wash after 30 mins. For skin: Mix with rose water into a face mask. Internally: 1/2 tsp in warm water.",
    storage: "Store in a cool, dry place away from moisture and direct light.",
    shelfLife: "12 Months from date of packing",
    isVeg: true,
    badge: "Go-To Pick",
    available: true,
    stock: 75,
    rating: 4.9,
    reviewCount: 112,
    isFeatured: false
  },
  {
    name: "Neem & Turmeric Herbal Face Ubtan",
    slug: "neem-turmeric-face-powder",
    sku: "SKN-NEM-100",
    category: "skin-hair",
    price: 280,
    compareAtPrice: 320,
    discount: 12,
    weight: "100g",
    image: "https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Traditional ubtan with wild neem leaf, raw turmeric, sandalwood, and rose petal powder.",
    description: "Inspired by the bridal ubtan traditions of South India. This dry face powder cleanses, brightens, and soothes. Neem fights bacteria and acne, turmeric reduces pigmentation, sandalwood soothes inflammation, and rose petals impart a natural glow.",
    ingredients: ["Wild Neem Leaf Powder", "Raw Turmeric Powder", "Sandalwood Powder", "Rose Petal Powder", "Chickpea Flour (Fine)", "Red Lentil Flour"],
    howToUse: "Mix 1 tsp ubtan with raw milk or rose water into a smooth paste. Apply to face, massage gently in circular motions, leave for 10-15 min, rinse with lukewarm water.",
    storage: "Store in a dry, airtight container away from humidity.",
    shelfLife: "10 Months from date of packing",
    isVeg: true,
    badge: "Seasonal",
    available: true,
    stock: 60,
    rating: 4.9,
    reviewCount: 73,
    isFeatured: false
  },

  // Combo Offers (as isCombo products)
  {
    name: "Thokku Heritage Trio Pack",
    slug: "thokku-heritage-trio",
    sku: "CMB-TR-3X250",
    category: "combos",
    price: 690,
    compareAtPrice: 790,
    discount: 13,
    weight: "3 × 250g Jars",
    image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "Mango + Tomato + Garlic Relishes gift pack with exclusive savings.",
    description: "Our top three handcrafted thokkus in one beautiful gift pack. Includes Kili Mooku Mango, Country Tomato, and Mountain Garlic Thokku.",
    badge: "Most Popular",
    isVeg: true,
    isCombo: true,
    productIds: ["mango-thokku", "tomato-thokku", "poondu-milagu-thokku"],
    available: true,
    stock: 40,
    rating: 4.9,
    reviewCount: 92,
    isFeatured: true
  },
  {
    name: "Family Vitality & Ghee Box",
    slug: "wellness-starter-box",
    sku: "CMB-VIT-GHE",
    category: "combos",
    price: 940,
    compareAtPrice: 1090,
    discount: 14,
    weight: "350ml Ghee + 500g Mix",
    image: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1628088062854-d1870b4553da?q=80&w=800&auto=format&fit=crop"],
    shortDescription: "A2 Bilona Ghee + Sprouted Sathu Maavu",
    description: "Everything a conscious home needs for wholesome breakfasts and nourishing dinners. Pure Vedic A2 bilona ghee combined with sprouted 14-grain porridge.",
    badge: "Value Set",
    isVeg: true,
    isCombo: true,
    productIds: ["a2-bilona-ghee", "sprouted-health-mix"],
    available: true,
    stock: 35,
    rating: 5.0,
    reviewCount: 84,
    isFeatured: true
  }
];
